version: '3.3'

services:

  ghost:
    image: ghost:5.75
    container_name: ghost
    restart: unless-stopped    
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: p4ssw0rd
      database__connection__database: ghost
      url: 'http://localhost:8200'
    ports:
      - '8200:2368'
    depends_on:
      - db
    volumes:
      - ./ghost:/var/lib/ghost/content

  db:
    image: mariadb:11.2
    container_name: ghost-db    
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd
    volumes:
      - ./ghost_db:/var/lib/mysql

